#!/usr/bin/env bash
#
# Since: January, 2019
# Author: gvenzl
# Name: csv2db
# Description: csv2db shell wrapper
#
# Copyright 2019 Gerald Venzl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Check whether python 3 is available
if command -v python3 &>/dev/null; then
    ./src/python/csv2db.py "$@"
else
    echo "Python 3 is not installed, please install Python 3 first."
    echo "For more information see https://www.python.org/downloads/"
fi
