name: Publish to Container Registries

on: [push]
#  workflow_run:
#    workflows: ["Publish csv2db distribution to PyPI"]
#    types:
#      - completed

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Get Latest Version tag'
        id: latestversiontag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Build image
        run: |
          podman build -f Dockerfile -t gvenzl/csv2db:${{ steps.latestversiontag.outputs.tag }}
          podman tag gvenzl/csv2db:${{ steps.latestversiontag.outputs.tag }} gvenzl/csv2db:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_PASSSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gvenzl/csv2db:latest
            gvenzl/csv2db:latestversiontag
            ghcr.io/gvenzl/csv2db:latest
            ghcr.io/gvenzl/csv2db:latestversiontag
