name: Publish to Container Registries

on: [push]
#  workflow_run:
#    workflows: ["Publish csv2db distribution to PyPI"]
#    types:
#      - completed

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          podman build -f Dockerfile -t gvenzl/csv2db:$LATEST_TAG
          podman tag gvenzl/csv2db:$LATEST_TAG gvenzl/csv2db:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_PASSSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gvenzl/csv2db:latest
            gvenzl/csv2db:$LATEST_TAG
            ghcr.io/gvenzl/csv2db:latest
            ghcr.io/gvenzl/csv2db:$LATEST_TAG
