name: Publish csv2db distribution to TestPyPI

# Trigger only when a new tag is created (vN.N.N)
on:
  push:
    tags:
      - v*.*.*

jobs:

  build:
    name: Build csv2db distribution package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: >-
          python3 -m pip install build --user

      - name: Build a binary wheel and source tarball
        run: python3 -m build

      - name: Store distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distros
          path: dist/

  publish-to-testpypi:
    name: Publish csv2db distribution to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/csv2db
    permissions:
      id-token: write

    steps:
      - name: Download package distros
        uses: actions/download-artifact@v3
        with:
          name: python-package-distros
          path: dist/

      - name: Publish distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
